(function(){
  "use strict";
  var sourceMeta=document.querySelector('meta[name="neo-source-url"]');
  var sourceLocation=sourceMeta?sourceMeta.content:location.href;
  var id=new URL(sourceLocation,document.baseURI).searchParams.get("tool")||"neo-guide";
  var root=document.querySelector("[data-tool-root]");
  var title=document.querySelector("[data-title]");
  var subtitle=document.querySelector("[data-subtitle]");
  var names={markdown:"Markdown","file-converter":"File Converter","clock-tools":"Clock",camera:"Camera","color-picker":"Color Picker","emoji-selector":"Emoji Selector","screenshot-studio":"Screenshot Studio","clipboard-manager":"Clipboard Manager",magnifier:"Magnifier","system-monitor":"System Monitor","storage-editor":"Storage Editor","developer-tools":"Developer Tools","virtual-machine-manager":"Virtual Machines","app-creator":"App Creator",rhythms:"Rhythms",cmatrix:"CMatrix","mode-switcher":"Mode Switcher",shortcuts:"Shortcuts","default-apps":"Default Apps","session-manager":"Session","neo-guide":"NEO OS Guide","intro-tour":"Intro Tour","whats-new":"What’s New"};
  title.textContent=names[id]||"NEO Tool";document.title=title.textContent+" · NEO OS";
  function html(source){root.innerHTML=source}
  function status(message){var node=root.querySelector(".status");if(node)node.textContent=message}
  function escape(value){return String(value||"").replace(/[&<>]/g,function(ch){return({"&":"&amp;","<":"&lt;",">":"&gt;"})[ch]})}
  function download(name,blob){var url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(function(){URL.revokeObjectURL(url)},1000)}
  function shell(){try{return parent.NEO_SHELL||null}catch(_error){return null}}
  function simplePage(heading,copy,items){subtitle.textContent=copy;html('<section class="card hero"><h2>'+heading+'</h2><p>'+copy+'</p></section><section class="card">'+items.map(function(item){return'<div class="metric"><strong>'+item[0]+'</strong><span class="muted">'+item[1]+'</span></div>'}).join("")+'</section>')}

  if(id==="markdown"){
    subtitle.textContent="Private, live Markdown preview";html('<div class="grid"><section class="card"><label>Markdown<textarea data-source># Hello from NEO\n\nWrite **Markdown** here.</textarea></label><div class="actions"><button data-save>Download .md</button></div></section><section class="card"><h2>Preview</h2><div class="preview" data-preview></div></section></div>');
    var source=root.querySelector("[data-source]"),preview=root.querySelector("[data-preview]");function render(){var value=escape(source.value).replace(/^### (.*)$/gm,"<h3>$1</h3>").replace(/^## (.*)$/gm,"<h2>$1</h2>").replace(/^# (.*)$/gm,"<h1>$1</h1>").replace(/\*\*(.*?)\*\*/g,"<strong>$1</strong>").replace(/\*(.*?)\*/g,"<em>$1</em>").replace(/`([^`]+)`/g,"<code>$1</code>").replace(/\n/g,"<br>");preview.innerHTML=value}source.addEventListener("input",render);root.querySelector("[data-save]").onclick=function(){download("note.md",new Blob([source.value],{type:"text/markdown"}))};render();
  }else if(id==="clock-tools"){
    subtitle.textContent="Clock, stopwatch, and timer";html('<section class="card hero"><div class="clock" data-clock>--:--:--</div><p data-date></p></section><div class="grid"><section class="card"><h2>Stopwatch</h2><div class="clock" style="font-size:42px" data-stopwatch>00:00.0</div><div class="actions"><button data-start>Start</button><button data-reset>Reset</button></div></section><section class="card"><h2>Timer</h2><label>Minutes<input type="number" min="1" max="180" value="5" data-minutes></label><div class="actions"><button data-timer>Start timer</button></div><p class="status"></p></section></div>');
    setInterval(function(){var now=new Date();root.querySelector("[data-clock]").textContent=now.toLocaleTimeString();root.querySelector("[data-date]").textContent=now.toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric",year:"numeric"})},250);var start=0,tick=0;root.querySelector("[data-start]").onclick=function(e){if(tick){clearInterval(tick);tick=0;e.target.textContent="Start"}else{start=Date.now();tick=setInterval(function(){var n=(Date.now()-start)/1000,mins=Math.floor(n/60);root.querySelector("[data-stopwatch]").textContent=String(mins).padStart(2,"0")+":"+(n%60).toFixed(1).padStart(4,"0")},100);e.target.textContent="Pause"}};root.querySelector("[data-reset]").onclick=function(){start=Date.now();root.querySelector("[data-stopwatch]").textContent="00:00.0"};root.querySelector("[data-timer]").onclick=function(){var end=Date.now()+Number(root.querySelector("[data-minutes]").value)*60000;status("Timer started");var timer=setInterval(function(){var left=Math.max(0,end-Date.now());status(Math.ceil(left/1000)+" seconds remaining");if(!left){clearInterval(timer);status("Timer finished");if(shell())shell().notify("Timer finished","Your NEO timer is complete.","bell")}},250)};
  }else if(id==="emoji-selector"){
    subtitle.textContent="Search and copy emoji";var emojis="😀 😃 😄 😁 😆 😅 😂 🙂 🙃 😉 😊 😎 🤩 🥳 😍 🤔 🫡 🤯 😴 😭 😡 👍 👎 👏 🙌 🫶 💪 ✨ ⭐ 🔥 ❤️ 💙 💚 💜 🖤 ✅ ❌ ⚡ ☀️ 🌙 🌈 🎮 🎵 🎬 💻 📱 🚀 🧠 🐱 🐶 🍕 🍔 ☕".split(" ");html('<section class="card"><label>Search<input type="search" placeholder="Filter emoji" data-search></label><div class="emoji-grid" data-grid></div><p class="status"></p></section>');var grid=root.querySelector("[data-grid]");emojis.forEach(function(emoji){var b=document.createElement("button");b.textContent=emoji;b.title="Copy "+emoji;b.onclick=function(){navigator.clipboard.writeText(emoji).then(function(){status("Copied "+emoji)})};grid.appendChild(b)});root.querySelector("[data-search]").oninput=function(e){Array.from(grid.children).forEach(function(b){b.hidden=e.target.value&&b.textContent.indexOf(e.target.value)===-1})};
  }else if(id==="camera"){
    subtitle.textContent="Camera capture stays on this device";html('<section class="card"><div class="canvas-wrap"><video data-video autoplay playsinline muted></video><canvas data-canvas hidden></canvas></div><div class="actions"><button data-open>Start camera</button><button data-photo>Take photo</button><button data-download disabled>Download photo</button></div><p class="status"></p></section>');var video=root.querySelector("video"),canvas=root.querySelector("canvas");root.querySelector("[data-open]").onclick=function(){navigator.mediaDevices.getUserMedia({video:true,audio:false}).then(function(stream){video.srcObject=stream;status("Camera ready")}).catch(function(e){status(e.message)})};root.querySelector("[data-photo]").onclick=function(){canvas.width=video.videoWidth||1280;canvas.height=video.videoHeight||720;canvas.getContext("2d").drawImage(video,0,0,canvas.width,canvas.height);canvas.hidden=false;video.hidden=true;root.querySelector("[data-download]").disabled=false};root.querySelector("[data-download]").onclick=function(){canvas.toBlob(function(blob){download("neo-photo.png",blob)},"image/png")};
  }else if(id==="color-picker"){
    subtitle.textContent="Color and contrast tools";html('<div class="grid"><section class="card"><div class="swatch"></div><label>Color<input type="color" value="#72d8ff" data-color></label><label>Hex<input value="#72d8ff" data-hex></label><button data-copy>Copy</button><p class="status"></p></section><section class="card"><h2>Contrast preview</h2><div class="preview" data-contrast><h2>Readable text</h2><p>NEO OS color preview</p></div></section></div>');var color=root.querySelector("[data-color]"),hex=root.querySelector("[data-hex]");function paint(v){if(!/^#[0-9a-f]{6}$/i.test(v))return;color.value=v;hex.value=v;root.querySelector(".swatch").style.setProperty("--picked",v);root.querySelector("[data-contrast]").style.background=v}color.oninput=function(){paint(color.value)};hex.oninput=function(){paint(hex.value)};root.querySelector("[data-copy]").onclick=function(){navigator.clipboard.writeText(hex.value);status("Copied "+hex.value)};
  }else if(id==="file-converter"){
    subtitle.textContent="Convert local text and images";html('<section class="card"><label>Choose a file<input type="file" accept="text/*,image/png,image/jpeg,image/webp" data-file></label><label>Output format<select data-format><option value="txt">Plain text</option><option value="md">Markdown</option><option value="png">PNG image</option><option value="jpeg">JPEG image</option><option value="webp">WebP image</option></select></label><div class="actions"><button data-convert>Convert and download</button></div><p class="status"></p></section>');root.querySelector("[data-convert]").onclick=function(){var file=root.querySelector("[data-file]").files[0],format=root.querySelector("[data-format]").value;if(!file)return status("Choose a file first");if(file.type.indexOf("text/")===0){file.text().then(function(text){download(file.name.replace(/\.[^.]+$/,"")+"."+format,new Blob([text],{type:format==="md"?"text/markdown":"text/plain"}));status("Converted locally")});return}var image=new Image(),url=URL.createObjectURL(file);image.onload=function(){var c=document.createElement("canvas");c.width=image.naturalWidth;c.height=image.naturalHeight;c.getContext("2d").drawImage(image,0,0);c.toBlob(function(blob){download(file.name.replace(/\.[^.]+$/,"")+"."+format,blob);status("Converted locally");URL.revokeObjectURL(url)},"image/"+format,.92)};image.src=url};
  }else if(id==="magnifier"||id==="screenshot-studio"){
    subtitle.textContent=id==="magnifier"?"Inspect an image at any zoom":"Open and annotate a screenshot";html('<section class="card"><label>Open image<input type="file" accept="image/*" data-file></label><label>Zoom<input type="range" min="25" max="400" value="100" data-zoom></label><div class="canvas-wrap" style="overflow:auto"><img data-image alt=""></div><div class="actions"><button data-download>Download copy</button></div><p class="status"></p></section>');var img=root.querySelector("img"),loaded=null;root.querySelector("[data-file]").onchange=function(e){var file=e.target.files[0];if(!file)return;if(loaded)URL.revokeObjectURL(loaded);loaded=URL.createObjectURL(file);img.src=loaded;status("Image loaded")};root.querySelector("[data-zoom]").oninput=function(e){img.style.width=e.target.value+"%"};root.querySelector("[data-download]").onclick=function(){if(!img.src)return status("Open an image first");fetch(img.src).then(function(r){return r.blob()}).then(function(blob){download("neo-image.png",blob)})};
  }else if(id==="clipboard-manager"){
    subtitle.textContent="Private clipboard shelf";html('<section class="card"><div class="actions"><button data-paste>Read clipboard</button><button data-clear>Clear shelf</button></div><label>Clipboard shelf<textarea data-text placeholder="Clipboard text"></textarea></label><button data-copy>Copy shelf</button><p class="status"></p></section>');var text=root.querySelector("textarea");text.value=localStorage.getItem("neo_clipboard_shelf_v1")||"";text.oninput=function(){localStorage.setItem("neo_clipboard_shelf_v1",text.value)};root.querySelector("[data-paste]").onclick=function(){navigator.clipboard.readText().then(function(v){text.value=v;text.oninput();status("Clipboard imported")}).catch(function(){status("Clipboard permission was not granted")})};root.querySelector("[data-copy]").onclick=function(){navigator.clipboard.writeText(text.value).then(function(){status("Copied")})};root.querySelector("[data-clear]").onclick=function(){text.value="";text.oninput();status("Shelf cleared")};
  }else if(id==="system-monitor"||id==="developer-tools"){
    subtitle.textContent="Live browser and device diagnostics";html('<section class="card" data-metrics></section>');function metrics(){var memory=performance.memory;var rows=[["Logical processors",navigator.hardwareConcurrency||"Unavailable"],["Device memory",navigator.deviceMemory?navigator.deviceMemory+" GB":"Unavailable"],["Online",navigator.onLine?"Yes":"No"],["Viewport",innerWidth+" × "+innerHeight],["Pixel ratio",devicePixelRatio],["Page uptime",Math.round(performance.now()/1000)+"s"],["Heap used",memory?Math.round(memory.usedJSHeapSize/1048576)+" MB":"Unavailable"],["User agent",navigator.userAgent]];root.querySelector("[data-metrics]").innerHTML=rows.map(function(row){return'<div class="metric"><strong>'+row[0]+'</strong><span class="muted">'+escape(row[1])+'</span></div>'}).join("")}metrics();setInterval(metrics,1000);
  }else if(id==="storage-editor"){
    subtitle.textContent="Inspect NEO local storage";html('<section class="card"><label>Filter keys<input type="search" data-filter></label><div class="storage-list" data-list></div><p class="status"></p></section>');function storage(){var list=root.querySelector("[data-list]"),q=root.querySelector("[data-filter]").value.toLowerCase();list.innerHTML="";Object.keys(localStorage).sort().filter(function(k){return!q||k.toLowerCase().indexOf(q)!==-1}).forEach(function(k){var row=document.createElement("div");row.className="storage-item";var value=localStorage.getItem(k)||"";row.innerHTML='<code></code><input><button>Save</button>';row.querySelector("code").textContent=k;row.querySelector("input").value=value;row.querySelector("button").onclick=function(){localStorage.setItem(k,row.querySelector("input").value);status("Saved "+k)};list.appendChild(row)})}root.querySelector("[data-filter]").oninput=storage;storage();
  }else if(id==="app-creator"){
    subtitle.textContent="Add a site to the NEO launcher";html('<section class="card"><label>App name<input data-name placeholder="My app"></label><label>Website URL<input data-url type="url" placeholder="https://example.com"></label><div class="actions"><button data-create>Create app</button></div><p class="status"></p></section>');root.querySelector("[data-create]").onclick=function(){var s=shell(),name=root.querySelector("[data-name]").value.trim(),url=root.querySelector("[data-url]").value.trim();if(!s||!name||!url)return status("Enter a name and full URL");try{new URL(url)}catch(_e){return status("Enter a valid http or https URL")}try{s.installCustomApp({title:name,url:url,mode:"relay",icon:""});status("App added to the launcher")}catch(error){status(error.message||"Could not create app")}};
  }else if(id==="cmatrix"||id==="rhythms"){
    subtitle.textContent=id==="cmatrix"?"Animated terminal rain":"Audio-reactive style visualizer";html('<section class="card"><div class="canvas-wrap"><canvas></canvas></div></section>');var canvas=root.querySelector("canvas"),ctx=canvas.getContext("2d"),t=0;function size(){canvas.width=canvas.clientWidth||900;canvas.height=canvas.clientHeight||500}size();addEventListener("resize",size);function draw(){t++;ctx.fillStyle=id==="cmatrix"?"rgba(0,0,0,.12)":"rgba(3,6,12,.2)";ctx.fillRect(0,0,canvas.width,canvas.height);if(id==="cmatrix"){ctx.fillStyle="#39ff6f";ctx.font="16px monospace";for(var x=0;x<canvas.width;x+=18)ctx.fillText(String.fromCharCode(0x30A0+Math.random()*90),x,(t*5+x*7)%canvas.height)}else{for(var i=0;i<42;i++){var h=(Math.sin(t*.04+i*.7)+1)*.28*canvas.height+18;ctx.fillStyle="hsl("+(185+i*4)+" 85% 60%)";ctx.fillRect(i*canvas.width/42,canvas.height-h,Math.max(2,canvas.width/42-4),h)}}requestAnimationFrame(draw)}draw();
  }else if(id==="mode-switcher"){
    subtitle.textContent="Change performance and interface modes";html('<section class="card"><h2>Performance</h2><div class="actions"><button data-mode="normal">Normal</button><button data-mode="performance">Performance</button><button data-mode="ultimate">Ultimate</button></div><h2>Interface</h2><div class="actions"><button data-style="modern">Modern</button><button data-style="windows11">Windows 11</button><button data-style="retro">Retro</button><button data-style="kali">Kali</button></div><p class="status"></p></section>');root.onclick=function(e){var s=shell();if(!s)return;if(e.target.dataset.mode){s.setSetting("performanceMode",e.target.dataset.mode);status("Performance mode updated")}if(e.target.dataset.style){s.setSetting("interfaceStyle",e.target.dataset.style);status("Interface style updated")}};
  }else if(id==="shortcuts"){
    simplePage("Keyboard shortcuts","Fast navigation without leaving the keyboard",[["Space","Open application search"],["Ctrl","Open taskbar menu"],["Ctrl + F","Search settings"],["Alt + Q","Switch applications"],["Enter","Open selected result"],["Escape","Close menus or dialogs"]]);
  }else if(id==="default-apps"){
    simplePage("Default applications","NEO keeps its first-party apps as safe defaults",[["Web links","NEO Browser"],["Music","NEO Music"],["Video","Media Player"],["Files","Drive"],["Games","NEO Games"],["Notes","Notes"]]);
  }else if(id==="virtual-machine-manager"){
    simplePage("Virtual machines","Browser-based virtual machine launchers",[["Virtual x86","Open v86 from the Development category"],["Isolation","VM content runs inside its own app window"],["Storage","Disk images remain under your control"]]);
  }else if(id==="session-manager"){
    subtitle.textContent="Save and restore your local workspace";html('<section class="card hero"><h2>Session persistence</h2><p>NEO OS automatically remembers window positions and can restore autostart apps from Settings.</p><div class="actions"><button data-reload>Reload session</button><button data-reset>Reset layout</button></div></section>');root.querySelector("[data-reload]").onclick=function(){parent.location.reload()};root.querySelector("[data-reset]").onclick=function(){if(shell())shell().resetLayout()};
  }else if(id==="whats-new"){
    simplePage("What’s new","The complete organized library is now part of NEO OS",[["Applications","96 source capabilities mapped into NEO categories"],["Wallpapers","Classic, macOS, ChromeOS, live, and imported collections"],["Themes","More than 70 system-wide palettes"],["Settings","Privacy, notifications, autostart, network, gaming, and session panels"],["Launcher","Recent apps and category browsing"]]);
  }else if(id==="intro-tour"){
    simplePage("Welcome to NEO OS","A quick tour of the desktop",[["1. Apps","Open the launcher to browse recent apps and categories"],["2. Search","Type any app, action, or category"],["3. Personalize","Open Settings for themes, taskbar, privacy, and performance"],["4. Wallpapers","Use Wallpaper Engine for static, live, and imported media"],["5. Backup","Download a private local backup from the top bar or Settings"]]);
  }else{
    simplePage("NEO OS Guide","Everything is organized around fast local access",[["Applications","Browse by category or search instantly"],["Games","NEO Games renders its direct CDN catalog without the web proxy"],["Browser","DuckDuckGo search runs through the selectable Scramjet/WISP transport"],["Privacy","Ads and analytics are off by default"],["Personalization","Themes and wallpapers apply across supported first-party apps"],["Data","Your preferences and files remain on this device unless you export them"]]);
  }
})();
